server:
  port: 12573


spring:
  application:
    name: cloud-gateway
  cloud:
    #网关
    gateway:
      routes:
        - id: admin #路由器的ID，没有固定规则但要唯一，建议配合服务名
          uri: http://localhost:8081 #匹配后提供服务的路由地址
          predicates: #断言，路径相匹配进行路由
            - Path=/bds/api/admin/**
        - id: trace
          uri: http://localhost:8082
          predicates:
            - Path=/bds/api/trace/**
        - id: mes
          uri: http://localhost:8082
          predicates:
            - Path=/bds/api/mes/**



