# 开发环境配置
server:
  port: 8083
  servlet:
    # 应用的访问路径
    context-path: /bds/api/mes


# 日志配置
logging:
  level:
    com.badese: debug
    org.springframework: warn



spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  profiles:
    active: druid




# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ruoyi.project.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
#  helperDialect: mysql
  autoRuntimeDialect: true
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 



api:
  admin:
    url: http://localhost:12573
    login: http://localhost:12573/bds/api/admin/login